sudo: false  # Use travis' container based infra
language: python
dist: xenial
# Versions are deliberately out of order to get a diverse sample first
python:
  - 3.7
  - 2.7
  - 3.5
  - 3.6
  - pypy3.5
cache:
  directories:
    - $PWD/wheelhouse  # cache the dependencies
env:
  global:
    - export PIP_FIND_LINKS=$PWD/wheelhouse
install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt
script: python setup.py test
